### ISSUE TITLE
consider moving to `enum class` when possible

### ISSUE THREAD

**Issue by MonsieurNicolas** [xdrpp/xdrpp#16]
C++ 11 can make enums type safe.

Recently we spotted a mistake in our code base (luckily no impact):
https://github.com/stellar/stellar-core/pull/1738/commits/9d832c5f259d02c0b286f7a46b40ce413945de15#diff-8449113f1d4140770b4c3361b6997826L252

Basically, the XDR is defined as:
```
enum PublicKeyType
{
    PUBLIC_KEY_TYPE_ED25519 = KEY_TYPE_ED25519
};

enum SignerKeyType
{
    SIGNER_KEY_TYPE_ED25519 = KEY_TYPE_ED25519,
    SIGNER_KEY_TYPE_PRE_AUTH_TX = KEY_TYPE_PRE_AUTH_TX,
    SIGNER_KEY_TYPE_HASH_X = KEY_TYPE_HASH_X
};

union PublicKey switch (PublicKeyType type)
{
case PUBLIC_KEY_TYPE_ED25519:
    uint256 ed25519;
};
```
and the resulting generated c++ uses old style enums:
```c++
enum PublicKeyType : std::int32_t { ...
```

It would be nice to instead generate enums as:
```c++
enum class PublicKeyType : std::int32_t { ...
```

A few implications:
* we would have to always specify the enum type in code (so referencing naked enum values would stop working), this is acceptable.
* when using a value in generated code, it's probably fine to perform a blanket cast to `std::int32_t`, so that enums defined like the one above will "just work", I think by doing something like:
```c++
enum class PublicKeyType : std::int32_t {
  PUBLIC_KEY_TYPE_ED25519 = (std::int32_t)CryptoKeyType::KEY_TYPE_ED25519,
};
``
* as XDR doesn't support enum namespacing, to ensure compliance with the xdr spec, the xdr compiler would still have to keep track of enums (and enum values) in a global map
* we would get type safety when performing comparisons between enum values (or require people to explicitly cast)

Thoughts?

**Comment by stanford-scs** [comment]
We discussed this early on.  The problem is that it either breaks XDR compatibility or breaks separate compilation.  The XDR language itself does not allow the C++ `::` member syntax.  xdrc allows them as an extension, but if we use this extension in our .x files, they will not be compatible with other compilers or languages, which is a huge negative.  Also, xdrc would fail to compile almost any existing RFC-compliant XDR file, as it would be missing the `EnumType::` in many union case labels.

The alternative would be to have xdrc insert the enum type qualifier automatically.  But to do this, it would need to know of all enums, so that it would know, e.g., to prefix every occurence of `KEY_TYPE_ED25519` with `CryptoKeyType::`.  That's not completely ridiculous--my go XDR compiler, goxdr, does compile a whole bunch of XDR files down to one go file.  But go compilation is a lot faster, so there's much less of a penalty for including a bunch of XDR types that you don't need.  Putting everything together into one file is not a very C++ way of doing things, and is even worse for things like scaffolding.

**Comment by MonsieurNicolas** [comment]
no, I think what we discussed earlier was indeed an extension to the XDR spec (not compatible), here what I am talking about doesn't involve any change in XDR specs, and only changes the generated code.


> The alternative would be to have xdrc insert the enum type qualifier automatically. But to do this, it would need to know of all enums, so that it would know, e.g., to prefix every occurence of KEY_TYPE_ED25519 with CryptoKeyType::.

This is what I am proposing

> Putting everything together into one file is not a very C++ way of doing things, and is even worse for things like scaffolding.

I am not sure I understand why we'd need to put everything in one file: if we assume RFC compliance, we know there is a single enum containing any given value, and that it has to be included within the `%#include` chain leading to the use of the enum value (not strictly XDR spec but seems reasonable to require people to include what they use)...

I think the change implies that the xdr compiler would have to load those intermediate includes (I don't think it needs to right now), if this is too much of a pain, maybe giving hints on `.x` dependencies would be easier to support, something like `%include xdr/Stellar-ledger-entries.x` ?
So I could see doing things like:
```
%include "Stellar-ledger-entries.x"
```
That ends up both parsing the `.x` file and generating a C++ `#include ...`

or maybe simply
```
%include "Stellar-ledger-entries.x"
%#include "xdr/Stellar-ledger-entries.h"
```
not as pretty, but practical (as it lets developers define which headers they want to include, generated or not)

**Comment by stanford-scs** [comment]
Well first off, % starts a literal line, which is an extension that Sun's old RPC compiler had.  We'd probably want some other syntax.  Then we'd have to deal with recursive includes, how this interacts with the namespace extension we already have, how this interacts with other RPC compilers (which should still ideally be able to parse the Stellar .x files) and so forth.

I'm pretty sceptical that the complexity would be worth it.

An alternative would be to streamline the Stellar XDR protocol, which currently has way more enums than it probably needs.  For instance, we should probably have only one kind of key, where accounts and signers allow different subsets of the known key types.  Protocol simplification would probably go a long way towards avoiding these kinds of bugs.

**Comment by stanford-scs** [comment]
This issue is worth revisiting when xdrpp moves to C++20, because of the `using enum` syntax.  Until then, however, I'm not going to fix it, particularly given people's desire for xdrc to be more rather than less RFC-compliant.
