### ISSUE TITLE
xdrc Accepts Enum with Trailing Comma

### ISSUE THREAD

**Issue by jonjove** [xdrpp/xdrpp#26]
Originally observed by @overcat in https://github.com/stellar/stellar-core/issues/2954.

xdrc should either
- fully comply with [RFC-4506](https://tools.ietf.org/html/rfc4506#page-17) and reject this case
- omit a warning to inform the user that there is an issue.

I prefer the first option if possible.

**Comment by stanford-scs** [comment]
This has been fixed in master by adding a `-pedantic` flag for strict RFC4506 adherence.
